# Informations sur le projet
sonar.projectKey=MonProjet
sonar.projectName=MonProjet

# URL du serveur SonarQube
sonar.host.url=http://localhost:9000

# Ton token utilisateur
sonar.login=squ_c0f99f1505878faabb3028bc304e130d7f7299ad

# Dossier contenant le code source
sonar.sources=src

# Dossier contenant les classes compilées
sonar.java.binaries=target/classes
